{ ... }:
{
  imports = [
    ./affinity.nix
    ./btop.nix
    ./chromium.nix
    ./dictation.nix
    ./direnv.nix
    ./web-apps
    ./eza.nix
    ./fd.nix
    ./firefox.nix
    ./fuzzel.nix
    ./fzf.nix
    ./git.nix
    ./ghostty.nix
    ./kdrive.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./nvim.nix
    ./qnap.nix
    ./qutebrowser
    ./rbw.nix
    ./ripgrep.nix
    ./sqlit.nix
    ./ssh.nix
    ./starship.nix
    ./table-plus.nix
    ./vnc.nix
    ./yubikey.nix
    ./zsh.nix
  ];
}
